### ISSUE TITLE
Devrig: window.VCSComposition_daily_baseline not set after babel plugin update

### ISSUE THREAD

**Issue by olafal0** [daily-co/daily-vcs#3]
When running `yarn run open-browser daily:baseline`, I get an alert "Couldn't find a Daily VCS composition using the standard naming pattern." Inspecting `window` keys confirms that `VCSComposition_daily_baseline` is not set. This issue can be fixed by reverting

```json
"@babel/plugin-transform-class-properties": "^7.22.5",
```

back to

```json
"@babel/plugin-proposal-class-properties": "^7.18.6",
```

in `js/package.json`.

The diff (`npm diff --diff=@babel/plugin-proposal-class-properties@7.18.6 --diff=@babel/plugin-transform-class-properties@7.22.5`) doesn't seem to include changes beyond renaming and depending on different versions of babel helpers, so I couldn't find much as to the cause beyond "somewhere in babel".

**Comment by olafal0** [comment]
More info: it looks like the `@babel/plugin-proposal-class-properties` packages is referenced in `js/webpack.config.js`: https://github.com/daily-co/daily-vcs/blob/main/js/webpack.config.js#L83. This seems to be what the devrig is complaining about

**Comment by pojala** [comment]
Thanks very much for the report!

This should be fixed now ([commit link](https://github.com/daily-co/daily-vcs/commit/ada1f41af28cb98a535460ab219409e4d335640c)). The Babel plugins were unnecessary at this point, I've removed them from the setup.
